/* "Copyright (C) 1989, California Institute of Technology. 
     U. S. Government Sponsorship under NASA Contract 
   NAS7-918 is acknowledged." */


/************************************************************************
*                      TIME WARP SIMULATOR                 v2113        *
*	      Global Variable definitions file TWSD.C                   *
*	      (See file TWSD.H for the declarations)			*
*									*
*									*
* Modified   JJW 10/3/86;						*
* Unified    LVW 10/6/86;						*
* unify with twsd.h JJW 1-9-87						*
*									*
*************************************************************************
*  DO NOT edit this file. All changes should be made in TWSD.H
*  which is now read by this file to get the data
*
*
************************************************************************/
	
#include "twcommon.h"
#include "tws.h"
static char twsdid[] = "%W%\t%G%";

/* select definition rather than declaration */
#define DEF

#include "twsd.h"

         
