#	Copyright (C) 1989, 1991, California Institute of Technology.
#		U. S. Government Sponsorship under NASA Contract NAS7-918
#		is acknowledged.
#
default:
	@echo "Usage is 'make <system>' where system is sun, sun4, or sun386"

sun:
	(cd Sun; make all)

sun4:
	(cd Sun4; make all)

sun386:
	(cd Sun386; make all)

bf_mach:
	(cd BF_MACH; make all)

clean:
	(cd Sun; make clean)
	(cd Sun4; make clean)
	(cd Sun386; make clean)
	(cd BF_MACH; make clean)

