#	Copyright (C) 1989, 1991, California Institute of Technology.
#		U. S. Government Sponsorship under NASA Contract NAS7-918
#		is acknowledged.
#

all:		gvtfilter ispeeder 

gvtfilter:
		cc -o gvtfilter  ../gvtfilter.c

ispeeder:
		cc -o ispeeder  ../ispeeder.c

clean:
		rm -f *.o


