#define k 1.38e-16  /* Boltzmann's constant */

typedef struct
{
    long	N ;
    double	time ;
    double      avgKE ;
    double	avgKECM ;
    double      stdDevKE ;
}
ThermData ;

ThermData computeThermData (/* Accumulator */) ;


/* This IO protocol automatically generated by "structIO", version 0.13 */
/* by Brian Beckman, JPL, Caltech, 8 Dec 1988                            */
/* IO protocol implementation stored in the file ThermDataIO.c */

void printThermData (/* ThermData */) ;
ThermData scanThermData () ;

void writeThermData (/* ThermData */) ;
ThermData readThermData () ;

void vprintThermData (/* ThermData */) ;
ThermData vscanThermData () ;


void fprintThermData (/* FILE*, ThermData */) ;
ThermData fscanThermData (/* FILE* */) ;

void fwriteThermData (/* FILE*, ThermData */) ;
ThermData freadThermData (/* FILE* */) ;

void fvprintThermData (/* FILE*, ThermData */) ;
ThermData fvscanThermData (/* FILE* */) ;
